MusicEshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from shop import views
from django.urls import path, include





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('addToCart/<int:i_id>/', views.addToCart, name="addToCart"),
    path('deleteFromCart/<int:i_id>/', views.deleteFromCart, name="deleteFromCart"),
    path('cart/', views.cart, name="cart"),
    path('cart/discount/<int:percent>/', views.discount, name="discount"),
    path('cart/discount/<int:percent>/<str:query>', views.discount, name="discount"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('instruments/', views.instruments, name="instruments"),
    path('add/', views.add, name="add"),
    path('payment/', views.payment, name="payment"),
    path('paymentcomplete/', views.final, name="final"),
    path('paymentcompleteview/', views.finalview, name="finalview"),

    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/profile/", views.loginView, name="loginView"),
    path("logout/", views.logoutView, name="logoutView"),

    path('categories/', views.categories, name="categories"),
    path("categories/zhichani/", views.zicani, name="zicani"),
    path("categories/duvachki/", views.duvacki, name="duvacki"),
    path("categories/udarni/", views.udarni, name="udarni"),
    path("categories/klavijatura/", views.klavijatura, name="klavijatura"),

    path("categories/zhichani/violina/", views.violina, name="violina"),
    path("categories/zhichani/gitara/", views.gitara, name="gitara"),
    path("categories/zhichani/kontrabas/", views.kontrabas, name="kontrabas"),
    path("categories/zhichani/harfa/", views.harfa, name="harfa"),
    path("categories/zhichani/mandolina/", views.mandolina, name="mandolina"),
    path("categories/zhichani/violoncelo/", views.violoncelo, name="violoncelo"),
    path("categories/duvachki/flejta/", views.flejta, name="flejta"),
    path("categories/duvachki/klarinet/", views.klarinet, name="klarinet"),
    path("categories/duvachki/truba/", views.truba, name="truba"),
    path("categories/duvachki/saksofon/", views.saksofon, name="saksofon"),
    path("categories/udarni/tapani/", views.tapani, name="tapani"),
    path("categories/udarni/ksilofon/", views.ksilofon, name="ksilofon"),
    path("categories/udarni/kahoni/", views.kahoni, name="kahoni"),
    path("categories/klavijatura/pijano/", views.pijano, name="pijano"),
    path("categories/klavijatura/harmonika/", views.harmonika, name="harmonika"),
    path("categories/klavijatura/sintisajzer/", views.sintisajzer, name="sintisajzer"),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

shop/models.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Instrument(models.Model):
    class Categories(models.TextChoices):
        ZHICHANI = "Zhichani", "Жичани"
        DUVACHKI = "Duvachki", "Дувачки"
        UDARNI = "Udarni", "Ударни"
        KLAVIJATURA = "Klavijatura", "Клавијатура"

    class Types(models.TextChoices):
        VIOLINA = "Violina", "Виолина"
        GITARA = "Gitara", "Гитара"
        KONTRABAS = "Kontrabas", "Контрабас"
        HARFA = "Harfa", "Харфа"
        MANDOLINA = "Mandolina", "Мандолина"
        VIOLONCELO = "Violoncelo", "Виолончело"
        FLEJTA = "Flejta", "Флејта"
        KLARINET = "Klarinet", "Кларинет"
        TRUBA = "Truba", "Труба"
        SAKSOFON = "Saksofon", "Саксофон"
        TAPANI = "Tapani", "Тапани"
        KSILOFON = "Ksilofon", "Ксилофон"
        KAHONI = "Kahoni", "Кахони"
        PIJANO = "Pijano", "Пијано"
        HARMONIKA = "Harmonika", "Хармоника"
        SINTISAJZER = "Sintisajzer", "Синтисајзер"

    category = models.CharField(max_length=11, choices=Categories.choices, default=Categories.ZHICHANI)
    type = models.CharField(max_length=12, choices=Types.choices, default=Types.GITARA)
    manufacturer = models.CharField(max_length=80)
    model = models.CharField(max_length=80)
    description = models.TextField(blank=True, null=True)
    quantity = models.IntegerField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return f'{self.manufacturer} {self.model}'


class Cart(models.Model):
    usersession = models.CharField(max_length=50)
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE)
    # quantity = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.usersession} {self.instrument}'


class Customer(models.Model):
    class Payment(models.TextChoices):
        CASH = "Cash", "Во готово"
        CARD = "Credit", "Со кредитна картичка"
        BANK = "Bank", "Преку банкарска трансакција"

    customersession = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    municipality = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    paymenttype = models.CharField(max_length=10, choices=Payment.choices, default=Payment.CASH)
    cardholdername = models.CharField(max_length=50, null=True, blank=True)
    cardnumber = models.CharField(max_length=16, null=True, blank=True)
    cardexpiry = models.CharField(max_length=5, null=True, blank=True)
    cardcvv = models.CharField(max_length=3, null=True, blank=True)

    def __str__(self):
        return f'{self.name} {self.surname}'


class Receipt(models.Model):
    receipt = models.IntegerField()
    session = models.CharField(max_length=50)
    discountpercent = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return f'{self.receipt}'


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE)
    products = models.ManyToManyField(Instrument)
    # products = ArrayField(models.IntegerField(null=True, blank=True), null=True, blank=True)
    # cart = models.ManyToManyField(Cart)
    totalprice = models.IntegerField()
    orderdate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.customer}'


class Message(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    message = models.TextField()

shop/forms.py
from django import forms
from .models import Instrument, Customer, Message


class InstrumentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(InstrumentForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Instrument
        fields = '__all__'

class CustomerForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Customer
        exclude = ("customersession",)


class MessageForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Message
        fields = '__all__'

shop/views.py
from django.shortcuts import render, redirect, reverse
from .models import Instrument, Cart, Order, Receipt, Customer
from django.contrib.sessions.models import Session
from django.contrib.auth.signals import user_logged_in, user_logged_out, user_login_failed
from django.contrib.auth.models import AnonymousUser, User
from .forms import InstrumentForm, CustomerForm, MessageForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


def index(request):
    if request.user.is_anonymous:
        request.session['cached_session_key'] = request.session.session_key
    return render(request, "index.html")


def addToCart(request, i_id):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session

    session = request.session.session_key
    instrumentToAdd = Instrument.objects.filter(pk=i_id)[0]
    newItem = Cart(usersession=session, instrument=instrumentToAdd)
    newItem.save()
    return redirect('cart')


def deleteFromCart(request, i_id):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session

    session = request.session.session_key
    instrumentToDelete = Instrument.objects.filter(pk=i_id)[0]
    deleteItem = Cart.objects.filter(usersession=session, instrument=instrumentToDelete).all()
    deleteItem.delete()
    return redirect('cart')


def cart(request):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session
    for row in Cart.objects.all().reverse():
        if Cart.objects.filter(usersession=row.usersession).filter(instrument=row.instrument).count() > 1:
            row.delete()
    user = request.session.session_key
    productids = Cart.objects.filter(usersession=user).values("instrument")
    productids = list(productids)
    productids = [o['instrument'] for o in productids]
    products = Instrument.objects.filter(pk__in=productids)
    len = products.count()
    test = Receipt.objects.filter(session=user).count()
    if test == 0:
        recLen = Receipt.objects.count()
        receipt = Receipt(session=user, receipt=recLen + 1)
        receipt.save()

    recContext = Receipt.objects.filter(session=user).first()
    context = {"user": user, "products": products, "len": len, "receipt": recContext}

    if recContext.discountpercent != None:
        percent = recContext.discountpercent
        context = {"user": user, "products": products, "len": len, "receipt": recContext, "percent": percent}

    return render(request, "cart.html", context)


def payment(request):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session

    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            if customer.paymenttype == "Credit":
                # prevent saving real card information for prototype
                customer.cardholdername = 'Encrypted information'
                customer.cardnumber = 'Encrypted information'
                customer.cardexpiry = 'Encrypted information'
                customer.cardcvv = 'Encrypted information'
            customer.customersession = request.session.session_key
            form.save()
            return redirect('final')
    else:
        user = request.session.session_key
        productids = Cart.objects.filter(usersession=user).values("instrument")
        productids = list(productids)
        productids = [o['instrument'] for o in productids]
        products = Instrument.objects.filter(pk__in=productids)
        form = CustomerForm()
        receipt = Receipt.objects.filter(session=user).first()

    context = {"form": form, "products": products, "receipt": receipt}
    if receipt.discountpercent != None:
        percent = receipt.discountpercent / 100
        context = {"form": form, "products": products, "receipt": receipt, "percent": percent}

    return render(request, 'payment.html', context)


def final(request):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session

    sessionNow = request.session.session_key
    customer = Customer.objects.filter(customersession=sessionNow).first()
    receipt = Receipt.objects.filter(session=sessionNow).first()

    productids = Cart.objects.filter(usersession=sessionNow).values("instrument")
    productids = list(productids)
    productids = [o['instrument'] for o in productids]
    products = Instrument.objects.filter(pk__in=productids)
    total = 0
    for p in products:
        pr = Instrument.objects.get(pk=p.id)
        pr.quantity = pr.quantity - 1
        pr.save()
        total += p.price

    if receipt.discountpercent != None:
        percent1 = receipt.discountpercent / 100
        toReduce = total * percent1
        total -= toReduce

    total += 1000
    order = Order(customer=customer, receipt=receipt, totalprice=total)
    order.save()
    order.products.set(products)
    order.save()

    # context = {"total":total, "products":products, "customer":customer, "receipt":receipt}
    # return render(request, 'final.html', context=context)
    return redirect('finalview')


def finalview(request):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session

    sessionNow = request.session.session_key
    customer = Customer.objects.filter(customersession=sessionNow).first()
    receipt = Receipt.objects.filter(session=sessionNow).first()

    productids = Cart.objects.filter(usersession=sessionNow).values("instrument")
    productids = list(productids)
    productids = [o['instrument'] for o in productids]
    products = Instrument.objects.filter(pk__in=productids)
    total = 1000  # innitialy for shipment
    for p in products:
        total += p.price
    request.session.flush()
    context = {"total": total, "products": products, "customer": customer, "receipt": receipt}
    return render(request, 'final.html', context=context)


def discount(request, percent):
    # Check session
    if request.session.session_key == None:
        return redirect('index')
    # End check session
    user = request.session.session_key
    reciept = Receipt.objects.filter(session=user).first()
    reciept.discountpercent = percent
    reciept.save()
    strpercent = str(percent)
    return redirect(reverse('cart') + '?p=' + strpercent)


def categories(request):
    return render(request, 'categories.html')


def contact(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('contact') + '?sent=true')
    else:
        form = MessageForm()
        context = {"form": form}
        return render(request, 'contact.html', context)


def about(request):
    return render(request, 'about.html')


@login_required
def instruments(request):
    queryset = Instrument.objects.all()
    len1 = Instrument.objects.count()
    context = {"instruments": queryset, "len": len1}
    return render(request, 'instruments.html', context)


@login_required
def add(request):
    if request.method == 'POST':
        form = InstrumentForm(request.POST, request.FILES)
        if form.is_valid():
            instrument = form.save(commit=False)

            form.save()
            return redirect('add')
    else:
        form = InstrumentForm()

    context = {"form": form}
    return render(request, 'add.html', context)


def loginView(request):
    return redirect('index')


def logoutView(request):
    user = getattr(request, "user", None)
    if not getattr(user, "is_authenticated", True):
        user = None
    user_logged_out.send(sender=user.__class__, request=request, user=user)
    request.session.flush()
    if hasattr(request, "user"):
        request.user = AnonymousUser()
    return redirect('index')


def zicani(request):
    return render(request, 'products/zicani.html')


def duvacki(request):
    return render(request, 'products/duvacki.html')


def udarni(request):
    return render(request, 'products/udarni.html')


def klavijatura(request):
    return render(request, 'products/klavijatura.html')


def violina(request):
    products = Instrument.objects.filter(type="Violina")
    context = {"products": products}
    return render(request, 'products/zicani/violina.html', context)


def gitara(request):
    products = Instrument.objects.filter(type="Gitara")
    context = {"products": products}
    return render(request, 'products/zicani/gitara.html', context)


def kontrabas(request):
    products = Instrument.objects.filter(type="Kontrabas")
    context = {"products": products}
    return render(request, 'products/zicani/kontrabas.html', context)


def harfa(request):
    products = Instrument.objects.filter(type="Harfa")
    context = {"products": products}
    return render(request, 'products/zicani/harfa.html', context)


def mandolina(request):
    products = Instrument.objects.filter(type="Mandolina")
    context = {"products": products}
    return render(request, 'products/zicani/mandolina.html', context)


def violoncelo(request):
    products = Instrument.objects.filter(type="Violoncelo")
    context = {"products": products}
    return render(request, 'products/zicani/violoncelo.html', context)


def flejta(request):
    products = Instrument.objects.filter(type="Flejta")
    context = {"products": products}
    return render(request, 'products/duvacki/flejta.html', context)


def klarinet(request):
    products = Instrument.objects.filter(type="Klarinet")
    context = {"products": products}
    return render(request, 'products/duvacki/klarinet.html', context)


def saksofon(request):
    products = Instrument.objects.filter(type="Saksofon")

shop/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>Нешто важно за нас :)</h1>
    <p>Добредојдовте на нашата е-продавница за музички инструменти, каде што ќе најдете најголем избор на врвни музички
        инструменти на пазарот. Нашата цел е услужливост на нашите клиенти со највисоко квалитетни инструменти од
        светски познати производители.</p>

    <div class="row">
        <div class="col-8">
            <p>Сите наши инструменти се внимателно избрани и проверени за квалитет пред да бидат доставени до Вас. Ги
                сортираме по категории, што Ви олеснува да ги најдете инструментите кои Ви се потребни. Сите производи
                се придружени со опис, слики и спецификации.</p>
            <p>Нашата е-продавница има сигурен и лесен процес на наплата. Исто така, нудиме брза и сигурна достава на
                сите нарачки.</p>
            <p>Вашето задоволство е нашиот најголем приоритет. Доколку имате дополнителни прашања, тимот од стручни
                музичари и купувачи е подготвен да Ви помогне со било какви прашања или препораки, контактирајте не!</p>
        </div>
        <div class="col-4">
            <img id="abImg" src="/data/static/about.png">
        </div>
    </div>
    <style>
        p {
            text-align: justify;
            font-style: italic;
            font-weight: bold;
        }

        #about {
            color: white
        }

        #abImg {
            max-width: 100%;

        }
    </style>
{% endblock %}

shop/templates/contact.html
{% extends 'base.html' %}
{% block content %}

    <br>
    <div class="text-center">
        <h1>Имате некакво прашање?</h1>

        <form action="{% url 'contact' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Испрати</button>

        </form>

    </div>

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Вашата порака е испратена</h4>
                    <button onclick="closeMd()" type="button" class="btn btn2" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button onclick="closeMd()" id="close" type="button" class="btn btn-outline-dark"
                    >Во ред
                    </button>
                </div>
            </div>

        </div>
    </div>


    <style>
        h1 {
            font-style: italic;
        }

        .form-label {
            float: left;
            font-weight: bold;
            font-style: italic;
        }

        #contact {
            color: white
        }

        .btn2 {
            font-size: 1.6rem;
        }
    </style>

    <script>
        document.querySelector("label[for='id_name']").textContent = 'Име и презиме';
        document.querySelector("label[for='id_email']").textContent = 'Е-пошта';
        document.querySelector("label[for='id_message']").textContent = 'Вашата порака';
        const urlParams = new URLSearchParams(window.location.search);
        const myParam = urlParams.get('sent');

        $(document).ready(function () {
            if (myParam === "true") {
                send()
            }
        })


        function send() {
            {#var name = document.getElementById("name").value#}
            {#var email = document.getElementById("email").value#}
            {#var message = document.getElementById("message").value#}
            {#if (name != "" && email != "" && message != "") {#}
            $('#myModal').modal('show');
            {# } #}
        }

        function closeMd() {
            $('#myModal').modal('hide');
            {#var name = document.getElementById("name").value = ""#}
            {#var email = document.getElementById("email").value = ""#}
            {#var message = document.getElementById("message").value = ""#}
        }
    </script>

{% endblock %}

shop/templates/payment.html
{% extends 'base.html' %}
{% block content %}

    <br>
    <div class="row">
        <div class="col receipt">Сметка бр. <span id="rec_id"></span><span id="rec_id2"></span></div>
        <div class="col header1">Наплата</div>
        <div class="col"></div>
    </div>

    <br>

    <div class="row header2">
        <div class="col">1. Информации и адреса за испорака</div>
        <div class="col">2. Начин на плаќање</div>
        <div class="col"></div>
    </div>

    <br>



    <form action="{% url 'payment' %}" method="POST">
        <div class="row">
            <div class="col">
                {% csrf_token %}
                <p>
                    <label for="id_name">Име</label>
                    <input type="text" name="name" maxlength="50" class="form-control" required="" id="id_name">
                </p>

                <p>
                    <label for="id_surname">Презиме</label>
                    <input type="text" name="surname" maxlength="50" class="form-control" required="" id="id_surname">
                </p>

                <p>
                    <label for="id_email">Е-маил</label>
                    <input type="text" name="email" maxlength="50" class="form-control" required="" id="id_email">
                </p>

                <p>
                    <label for="id_phone">Телефон</label>
                    <input type="text" name="phone" maxlength="50" class="form-control" required="" id="id_phone">
                </p>

                <p>
                    <label for="id_city">Град</label>
                    <input type="text" name="city" maxlength="50" class="form-control" required="" id="id_city">
                </p>

                <p>
                    <label for="id_municipality">Општина</label>
                    <input type="text" name="municipality" maxlength="50" class="form-control" required=""
                           id="id_municipality">
                </p>

                <p>
                    <label for="id_address">Адреса</label>
                    <input type="text" name="address" maxlength="50" class="form-control" required="" id="id_address">
                </p>
            </div>

            <div class="col">
                <p>
                    <label for="id_paymenttype">Вид на плаќање</label>
                    <select onchange="changeFc()" name="paymenttype" class="form-select" id="id_paymenttype">
                        <option value="Cash" selected>Во готово</option>

                        <option value="Credit">Со кредитна картичка</option>

                        <option value="Bank">Преку банкарска трансакција</option>

                    </select>
                </p>

                <br>
                <p>
                    <input type="text" disabled placeholder="Cardholder Name" name="cardholdername" maxlength="50"
                           class="form-control" id="id_cardholdername">
                </p>

                <p>
                    <input type="text" disabled placeholder="Card number" name="cardnumber" maxlength="16"
                           class="form-control"
                           id="id_cardnumber">
                </p>

                <div class="row">
                    <div class="col">
                        <p>
                            <input type="text" disabled placeholder="MM/YY" name="cardexpiry" maxlength="5"
                                   class="form-control" id="id_cardexpiry">
                        </p>
                    </div>
                    <div class="col">
                        <p>
                            <input type="text" disabled placeholder="CVV" name="cardcvv" maxlength="3"
                                   class="form-control"
                                   id="id_cardcvv">
                        </p>
                    </div>
                </div>
                <br><br>
                <div class="bankInfo" id="bankInf">
                    <p><b>Информации за плаќање преку банкарска трансакција</b></p>
                    <p>Банка: Шпаркасе Банка</p>
                    <p>Трансакциска с-ка: 250101000660022</p>
                    <p>Дознака: Уплата за сметка број <i>(Број на сметката)</i></p>
                </div>
            </div>
            <div class="col">
                <div class="totalPrice">
                    <p id="t1">Вкупно за наплата:</p>
                    <p id="p2"><span class="formatMoney" id="t2">26,200</span> ден</p>
                </div>
                <br>
                <button id="bt2" class="btn btn-success">Нарачај</button>
            </div>

        </div>
    </form>
    <br>
    <a class="btn btn-secondary" href="{% url 'cart' %}">Назад кон кошничка</a>

    <script>
        var total = 0;
    </script>
    {% for p in products %}
        <script>
            total +=
            {{ p.price }}
        </script>
    {% endfor %}

    <h1 id="tt"></h1>
    <style>
        .row {
            text-align: -moz-center;
            text-align: -webkit-center;
        }

        .receipt {
            text-align: center;
            font-size: 2rem;
            font-weight: bold;
            background-color: lightgray;
            border: 2px solid black;
            border-radius: 15px;
        }

        .header1 {
            text-align: center;
            align-self: center;
            font-size: 2rem;
            font-weight: bold;
        }

        label {
            font-weight: bold;
            float: left;
        }

        .header2 {
            font-weight: bold;
            font-size: 1.1rem;
        }

        .totalPrice {
            padding-left: 20px;
            padding-right: 20px;
            width: max-content;
            text-align: center;
            align-self: center;
            font-weight: bold;
            font-size: 1.5rem;
            border: 2px solid black;
            border-radius: 15px;
        }

        #t1 {
            margin-top: 10px;
        }

        #p2 {
            text-align-last: end;
        }

        #bt2 {
            font-weight: bold;
            font-size: 1.5rem;
        }

        .bankInfo {
            opacity: 50%;
            text-align: left;
            padding: 10px;
        }

        .bnk {
            opacity: 100%;
            box-shadow: 3px 3px 10px gray;
            border: 2px solid black;
            border-radius: 15px;
        }


    </style>
    <script>
        var toReduce = 0
        {% if percent %}
            toReduce = total * {{ percent }}
        {% endif %}
        var year = new Date().getFullYear().toString()
        document.getElementById("t2").innerText = total + 1000 - toReduce // neli, za dostava :)
        document.getElementById("rec_id").innerText = {{ receipt.receipt }} +"/" + year.slice(2, 4)

        function changeFc() {
            var type = document.getElementById("id_paymenttype").value
            if (type === "Credit") {
                document.getElementById("id_cardholdername").removeAttribute("disabled")
                document.getElementById("id_cardnumber").removeAttribute("disabled")
                document.getElementById("id_cardexpiry").removeAttribute("disabled")
                document.getElementById("id_cardcvv").removeAttribute("disabled")
                document.getElementById("id_cardholdername").setAttribute("required", "")
                document.getElementById("id_cardnumber").setAttribute("required", "")
                document.getElementById("id_cardexpiry").setAttribute("required", "")
                document.getElementById("id_cardcvv").setAttribute("required", "")
            }
            if (type !== "Credit") {
                document.getElementById("id_cardholdername").value = ""
                document.getElementById("id_cardnumber").value = ""
                document.getElementById("id_cardexpiry").value = ""
                document.getElementById("id_cardcvv").value = ""
                document.getElementById("id_cardholdername").setAttribute("disabled", "")
                document.getElementById("id_cardnumber").setAttribute("disabled", "")
                document.getElementById("id_cardexpiry").setAttribute("disabled", "")
                document.getElementById("id_cardcvv").setAttribute("disabled", "")
                document.getElementById("id_cardholdername").removeAttribute("required")
                document.getElementById("id_cardnumber").removeAttribute("required")
                document.getElementById("id_cardexpiry").removeAttribute("required")
                document.getElementById("id_cardcvv").removeAttribute("required")

            }
            if (type === "Bank") {
                document.getElementById("bankInf").classList.add("bnk")
            }
            if (type !== "Bank") {
                document.getElementById("bankInf").classList.remove("bnk")
            }
        }

        $(document).ready(function () {
            $("#bt2").css({
                'width': ($("#t1").width() + 40 + 'px')
            });
        });
        const elements = document.getElementsByClassName("formatMoney");
        for (let i = 0; i < elements.length; i++) {
            const element = elements[i];
            const content = element.textContent;
            const formattedContent = Number(content).toLocaleString();
            element.textContent = formattedContent;
        }
    </script>
{% endblock %}